disabled_rules: # rule identifiers to exclude from running
  - todo
  - identifier_name
  - vertical_parameter_alignment
  - large_tuple

line_length:
  warning: 120
  error: 120

identifier_name:
  warning: 1
  error: 1

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods

